version: '3.8'

services:
    web:
        build: .
        container_name: KC-web
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: KC-db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: KC-phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db

volumes:
    db_data:
