version: '3.8'

services:
    web:
        build: .
        container_name: KC-web
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: KC-db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
